name: CI - Test & Coverage

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run tests with Jacoco
      run: ./gradlew test jacocoTestReport

    - name: Verify coverage meets minimum
      run: ./gradlew jacocoTestCoverageVerification

    - name: Generate coverage summary
      run: |
        COVERAGE=$(cat build/reports/jacoco/test/html/index.html | grep -oP 'Total.*?([0-9]+)%' | grep -oP '[0-9]+%' | head -1)
        echo "### 📊 Test Coverage: $COVERAGE" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Full report available in artifacts below" >> $GITHUB_STEP_SUMMARY

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: jacoco-report
        path: build/reports/jacoco/test/html/

    - name: Add coverage to PR comment
      uses: madrapps/jacoco-report@v1.6.1
      if: github.event_name == 'pull_request'
      with:
        paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 80
        min-coverage-changed-files: 80
